name: Run CI
on:
  pull_request:
    paths:
      - '**'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Enable Corepack before setting up Node
        run: corepack enable

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install and run CI
        working-directory: ./
        run: |
          yarn
          yarn run ci
