name: Publish Components Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: npm-publish-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            components:
              - 'packages/components/**'  

      - name: Enable Corepack before setting up Node
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install and run build
        working-directory: packages/components
        run: |
          yarn install --immutable
          yarn dbuild

      - name: Publish to npm
        if: steps.filter.outputs.components == 'true'
        run: npm publish
        working-directory: packages/components
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
